[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "3d77454878515d0a86d1b28c44d708cbe4aeb1e7"
os = "macos"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "673f9e3061c186ae5465cfa42f512ac87ccca8aaee2daefc8c51da1dfd1b7d71"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "89e891e790dece7773a390ce6eacf83df6b1cd3b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "0781e17e3733cb98a53656bacd82dab8cc068a0518944678071c1f123e16e78d"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "26bfaf17d71ae7ce92634597ad4b4c3fcdfc36fa"
libc = "musl"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "98e8492038d09bf7a2f5104af7712043d592d46b642146290d90bbb0c44c022c"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "31e55d546c45874e281310e24eff6e95597c1a0a"
os = "freebsd"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "8f9837e3e68437ce0c9c2f176d609476e93d833c3e912dbc779484c3c40982d8"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "powerpc64le"
git-tree-sha1 = "0f48ddecb9e1ef94b0a97524b0984415e4487563"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "256386c25b670eebe708b904f8fb8d30cb3af488d8165ea87c36c458371a33a7"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "riscv64"
git-tree-sha1 = "43d218c17e3ee154eda34f06019042c4ee17382a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "a5cdf9ec3e52a8244ea332841c098d0c7801c82a1be07deffcdc7a90f6e8539d"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "717538011e70031b218a6386d1284083ea592131"
os = "macos"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "4ccb8633c7eecf6d5740d941cb92e6fc98204b17c250ebc0bb2a1c7263182c66"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "1ed3d0deed543635354a2422804d5dc275b18de0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "952d1d64a177e42d0ff6c91176d952fdb514fb7095fbac264b74882cdd5dac77"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "b13d8a38152f036e37a5c8bb2b1f1c3e08cbd04f"
libc = "musl"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "b1ec71e38d8acc455f89383258cc4c05577671ac192d33721fbc04396ada4cb5"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "19f70c359fcfcf2ac6b11f70dad3aab7d64cfac1"
os = "freebsd"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "b3e605e8254c7b8edeb61479b7d6cbaa97985367e3e21b3094314b0deca31a27"
    url = "https://github.com/lgoettgens/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v201.40400.0+0/GAP_pkg_curlinterface.v201.40400.0.x86_64-unknown-freebsd.tar.gz"
